In [3]:
import pandas as pd

In [4]:
freddie_mae = pd.read_parquet(
    "../../01_original_data/fannie_mae_data/Freddie_Mae_2025Q1.parquet",
    engine="pyarrow",
)
freddie_mae.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388622 entries, 0 to 388621
Columns: 110 entries, 0 to 109
dtypes: float64(75), int64(14), object(21)
memory usage: 326.1+ MB

In [5]:
freddie_mae.head()

,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
0,NaN,139435503,12025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",NaN,6.625,6.625,282000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
1,NaN,139435503,22025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",NaN,6.625,6.625,282000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
2,NaN,139435503,32025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",NaN,6.625,6.625,282000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
3,NaN,139435504,12025,R,Other,Other,NaN,6.250,6.250,176000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
4,NaN,139435504,22025,R,Other,Other,NaN,6.250,6.250,176000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN

In [6]:
# Remove columns that are completely null
print(f"The shape of the dataset is: {freddie_mae.shape}")
total_nulls = freddie_mae.isna().sum()
total_no_of_rows = len(freddie_mae)
for column, null_count in total_nulls.items():
    if null_count / total_no_of_rows >= 0.99:
        freddie_mae = freddie_mae.rename(columns={column: "delete"})
    elif len(freddie_mae[column].unique().tolist()) <= 1:
        freddie_mae = freddie_mae.rename(columns={column: "delete"})

freddie_mae_clean = freddie_mae.drop(columns=["delete"])
print(f"The shape of the cleaned dataset is: {freddie_mae_clean.shape}")

The shape of the dataset is: (388622, 110)
The shape of the cleaned dataset is: (388622, 42)

In [7]:
freddie_mae_clean.head()

,1,2,3,4,5,7,8,9,11,12,...,40,41,48,72,73,78,80,85,86,101
0,139435503,12025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,282000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,7,N,A,N,7
1,139435503,22025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,282000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,248.63,1.0,N,7,N,A,N,7
2,139435503,32025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,281000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,250.00,1.0,N,7,N,A,N,7
3,139435504,12025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
4,139435504,22025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,0.00,NaN,N,7,N,A,N,7

In [8]:
# Rename columns based on data dictionary
freddie_mae_clean = freddie_mae_clean.rename(
    columns={
        "1": "reference_pool_id",
        "2": "monthly_reporting_period",
        "3": "channel",
        "4": "seller_name",
        "5": "servicer_name",
        "7": "original_interest_rate",
        "8": "current_interest_rate",
        "9": "upb_at_issuance",
        "11": "current_actual_upb",
        "12": "original_loan_term",
        "13": "origination_date",
        "14": "first_payment_date",
        "15": "loan_age",
        "16": "remaining_months_to_legal_maturity",
        "17": "remaining_months_to_maturity",
        "18": "maturity_date",
        "19": "original_loan_to_value_ltv",
        "20": "original_combined_loan_to_value_cltv",
        "21": "number_of_borrowers",
        "22": "debt_to_income_dti",
        "23": "borrower_credit_score_at_origination",
        "24": "co_borrower_credit_score_at_origination",
        "25": "first_time_home_buyer_indicator",
        "26": "loan_purpose",
        "27": "property_type",
        "28": "number_of_units",
        "29": "occupancy_status",
        "30": "property_state",
        "31": "metropolitan_statistical_area_msa",
        "32": "zip_code_short",
        "33": "mortgage_insurance_percentage",
        "34": "amortization_type",
        "35": "prepayment_penalty_indicator",
        "36": "interest_only_loan_indicator",
        "39": "current_loan_delinquency_status",
        "40": "loan_payment_history",
        "41": "modification_flag",
        "48": "unknown_from_46_and_72",
        "72": "mortgage_insurance_type",
        "73": "servicing_activity_indicator",
        "78": "special_eligibility_program",
        "80": "relocation_mortgage_indicator",
        "85": "property_valuation_method",
        "86": "high_balance_loan_indicator",
        "101": "borower_assistance_plan",
    }
)

In [9]:
freddie_mae_clean.sample(50)
# freddie_mae_clean[43]

,reference_pool_id,monthly_reporting_period,channel,seller_name,servicer_name,original_interest_rate,current_interest_rate,upb_at_issuance,current_actual_upb,original_loan_term,...,loan_payment_history,modification_flag,unknown_from_46_and_72,mortgage_insurance_type,servicing_activity_indicator,special_eligibility_program,relocation_mortgage_indicator,property_valuation_method,high_balance_loan_indicator,borower_assistance_plan
334271,139833431,32025,B,Other,Nationstar Mortgage LLC,7.000,7.000,150000.0,150000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,7,N,A,N,7
158216,139488286,32025,R,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",5.990,5.990,311000.0,310000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,450.66,NaN,N,7,N,A,N,7
153596,139486745,22025,B,Other,Nationstar Mortgage LLC,7.000,7.000,455000.0,455000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,0.00,NaN,N,7,N,A,N,7
276263,139650027,32025,R,Other,Nationstar Mortgage LLC,6.625,6.625,175000.0,175000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,0.00,NaN,N,7,N,W,N,7
329073,139828233,32025,C,Other,Other,7.125,7.125,100000.0,100000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
46732,139451094,12025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.000,6.000,316000.0,316000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,7,N,A,N,7
113013,139473206,22025,R,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",6.476,6.476,453000.0,452000.0,300,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,655.31,NaN,N,7,N,A,N,7
222684,139623238,22025,B,"United Wholesale Mortgage, LLC","United Wholesale Mortgage, LLC",6.999,6.999,574000.0,573000.0,348,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,W,N,7
355556,139854716,32025,C,"PennyMac Loan Services, LLC","PennyMac Loan Services, LLC",6.500,6.500,522000.0,480000.0,180,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
160033,139488892,32025,R,Other,Other,6.250,6.250,184000.0,184000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,175.50,NaN,N,H,N,A,N,7
5145,139437219,32025,R,U.S. Bank N.A.,U.S. Bank N.A.,7.125,7.125,403000.0,402000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,323.79,1.0,N,7,N,A,N,7
121314,139475974,32025,R,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",6.990,6.990,171000.0,171000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,141.14,NaN,N,7,N,W,N,7
264347,139644069,32025,R,Other,Other,7.500,7.500,176000.0,176000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,131.63,NaN,N,7,N,A,N,7
182745,139496471,22025,C,"PennyMac Loan Services, LLC","PennyMac Loan Services, LLC",6.750,6.750,234000.0,229000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,4644.57,NaN,N,7,N,A,N,7
2434,139436314,22025,R,Other,Other,6.250,6.250,371000.0,371000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,352.26,NaN,N,7,N,A,N,7
383092,139882252,32025,C,"PennyMac Loan Services, LLC","PennyMac Loan Services, LLC",6.500,6.500,147000.0,147000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
190678,139499117,32025,C,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",6.990,6.990,306000.0,304000.0,240,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,600.89,NaN,N,7,N,W,N,7
199404,139502028,32025,R,Other,PHH Mortgage Corporation,6.375,6.375,230000.0,228000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,217.50,1.0,N,7,N,A,N,7
245049,139634420,32025,C,Truist Bank,Truist Bank,6.625,6.625,435000.0,434000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,553.75,NaN,N,7,N,A,N,7
67540,139458034,32025,R,Other,"Planet Home Lending, LLC",6.500,6.500,294000.0,293000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,268.66,NaN,N,7,N,A,N,7
96120,139467570,32025,B,Other,Other,6.000,6.000,240000.0,240000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,238.93,NaN,N,H,N,A,N,7
239108,139631450,22025,R,Other,Nationstar Mortgage LLC,7.250,7.250,276000.0,276000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,H,N,A,N,7
52807,139453121,22025,R,"Guaranteed Rate, Inc.","Guaranteed Rate, Inc.",6.100,6.100,72000.0,71000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,70.54,NaN,N,H,N,A,N,7
231037,139627414,32025,R,Other,Nationstar Mortgage LLC,7.000,7.000,285000.0,285000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,0.00,NaN,N,7,N,A,N,7
211290,139617541,22025,C,Nationstar Mortgage LLC,Nationstar Mortgage LLC,7.250,7.250,325000.0,324000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,7,N,A,N,7
52396,139452984,12025,R,"CMG Mortgage, Inc","CMG Mortgage, Inc",6.500,6.500,384000.0,384000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
308640,139666216,22025,R,Other,Nationstar Mortgage LLC,6.990,6.990,130000.0,130000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
231506,139627649,22025,R,Other,Other,6.125,6.125,288000.0,287000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,H,N,A,N,7
227528,139625660,22025,C,Other,Other,5.750,5.750,146000.0,145000.0,180,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
201304,139502662,32025,C,"United Wholesale Mortgage, LLC","United Wholesale Mortgage, LLC",6.500,6.500,483000.0,482000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,439.00,1.0,N,7,N,A,N,7
153441,139486693,32025,R,"Movement Mortgage, LLC","Movement Mortgage, LLC",6.500,6.500,230000.0,230000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,209.03,NaN,N,7,N,A,N,7
254785,139639288,32025,B,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",7.875,7.875,216000.0,215000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,152.82,NaN,N,7,N,A,N,7
322154,139672973,22025,C,"CMG Mortgage, Inc","CMG Mortgage, Inc",6.625,6.625,538000.0,538000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,7,N,A,N,7
194680,139500453,12025,C,"PennyMac Loan Services, LLC","PennyMac Loan Services, LLC",7.250,7.250,416000.0,416000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
372051,139871211,32025,R,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",7.250,7.250,75000.0,74000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
93888,139466826,12025,R,"Wells Fargo Bank, N.A.","Wells Fargo Bank, N.A.",6.500,6.500,200000.0,200000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
76309,139460961,22025,R,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",6.500,6.500,99000.0,99000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,89.87,NaN,N,H,N,W,N,7
80134,139462237,32025,R,Other,PHH Mortgage Corporation,6.500,6.500,230000.0,229000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,210.19,NaN,N,7,N,A,N,7
345567,139844727,32025,R,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",6.990,6.990,120000.0,119000.0,180,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,W,N,7
297100,139660446,22025,C,NewRez LLC,New Residential Mortgage LLC,6.875,6.875,295000.0,295000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
326204,139825364,32025,R,"Movement Mortgage, LLC","Movement Mortgage, LLC",6.125,6.125,580000.0,580000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
372812,139871972,32025,C,"AmeriHome Mortgage Company, LLC","AmeriHome Mortgage Company, LLC",6.625,6.625,270000.0,269000.0,240,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
182512,139496393,22025,R,Other,Other,7.125,7.125,125000.0,125000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,100.28,1.0,N,H,N,A,N,7
49634,139452063,12025,R,"Movement Mortgage, LLC","Movement Mortgage, LLC",6.875,6.875,795000.0,795000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,7,N,A,N,7
125151,139477256,12025,R,Other,Other,6.625,6.625,105000.0,105000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,H,N,A,N,7
28590,139445042,32025,R,Other,Other,6.750,6.750,300000.0,299000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,462.05,NaN,N,7,N,W,N,7
79167,139461915,12025,C,Other,Other,6.875,6.875,125000.0,125000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,1.0,N,F,N,A,N,7
125473,139477363,22025,C,Other,Other,6.625,6.625,111000.0,111000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0000,N,0.00,1.0,N,7,N,A,N,7
349273,139848433,32025,R,Other,Other,6.800,6.800,75000.0,75000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX00,N,NaN,NaN,N,7,N,A,N,7
93986,139466858,32025,C,"United Wholesale Mortgage, LLC","United Wholesale Mortgage, LLC",5.625,5.625,456000.0,456000.0,360,...,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX000000,N,0.00,NaN,N,7,N,A,N,7

In [11]:
# len(freddie_mae_clean["unknown_from_46_and_72"].unique().tolist())
freddie_mae_clean["unknown_from_46_and_72"].value_counts()

unknown_from_46_and_72
0.00       34468
1000.00      107
500.00        74
264.68        54
252.04        50
           ...
513.75         1
516.53         1
1184.69        1
291.11         1
372.39         1
Name: count, Length: 73028, dtype: int64

In [41]:
freddie_mae_clean.to_parquet(
    "../../02_processed_data/freddie_mae_clean.parquet", index=False
)