In [210]:
import pandas as pd
import numpy as np

# Read climate and financial data
df = pd.read_csv("../../02_processed_data/FINAL_CLIMATE_FINANCIAL_DATA.csv", index_col=0)
df = df.rename(columns={"index_nsa": "hpi"})
df.head()

/var/folders/6q/jjdxqy5114dgzjyg60l84np80000gn/T/ipykernel_29626/2703862107.py:5: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../02_processed_data/FINAL_CLIMATE_FINANCIAL_DATA.csv", index_col=0)

,county_fips5,yr,hpi_change,hpi,state,flood_frequency,flood_property_damage,flood_duration_hours,heat_stress_index,drought_annual_mean_index,...,deaths_hurricane,injuries_hurricane,damage_hurricane,real_gdp,unemployment_rate,prop_rate,county_fips,total_home_purchase,total_amt_purchase,total_population
14,1001,2000,2.50,141.23,ALABAMA,1.0,200000.0,3.50,0.546615,-2.32,...,0.0,0.0,0.0,0,4.1,0.000,1001.0,831.0,72778000.0,44021.0
15,1001,2001,3.44,146.08,ALABAMA,2.0,37000.0,4.25,0.295779,1.43,...,0.0,0.0,0.0,1041239,4.1,0.000,1001.0,766.0,71592000.0,44889.0
16,1001,2002,2.67,149.98,ALABAMA,0.0,0.0,0.00,0.378973,-0.76,...,0.0,0.0,0.0,1080135,4.8,0.000,1001.0,730.0,78607000.0,45909.0
17,1001,2003,1.79,152.66,ALABAMA,2.0,58000.0,6.00,0.277611,2.39,...,0.0,0.0,0.0,1111465,5.0,0.245,1001.0,835.0,93128000.0,46800.0
18,1001,2004,2.92,157.12,ALABAMA,1.0,8000.0,3.50,0.411246,0.00,...,0.0,0.0,0.0,1283522,4.7,0.245,1001.0,908.0,111256000.0,48366.0

In [211]:
# Subset for data in California from 2018-2020
df_ca_2018_2020 = df[
    (df['yr'].between(2018, 2020)) & (df['state'] == 'CALIFORNIA') ]

In [212]:
df_ca_2018_2020.head()

,county_fips5,yr,hpi_change,hpi,state,flood_frequency,flood_property_damage,flood_duration_hours,heat_stress_index,drought_annual_mean_index,...,deaths_hurricane,injuries_hurricane,damage_hurricane,real_gdp,unemployment_rate,prop_rate,county_fips,total_home_purchase,total_amt_purchase,total_population
5428,6001,2018,8.97,2013.07,CALIFORNIA,17.0,0.0,8.13,0.267856,-2.01,...,0.0,0.0,0.0,135481671,3.1,1.230,6001.0,14179.0,9.439345e+09,1666596.0
5429,6001,2019,1.15,2036.27,CALIFORNIA,28.0,0.0,13.63,0.429874,0.28,...,0.0,0.0,0.0,139438051,3.0,1.241,6001.0,13728.0,9.617800e+09,1668412.0
5430,6001,2020,0.01,2036.42,CALIFORNIA,13.0,0.0,7.00,0.382561,-4.11,...,0.0,0.0,0.0,136360934,8.9,1.250,6001.0,13962.0,1.041741e+10,1680614.0
5460,6003,2018,0.16,214.28,CALIFORNIA,0.0,0.0,0.00,0.227558,-0.96,...,0.0,0.0,0.0,115488,4.6,1.000,6003.0,11.0,4.205000e+06,1081.0
5461,6003,2019,9.72,235.10,CALIFORNIA,0.0,0.0,0.00,0.199422,0.45,...,0.0,0.0,0.0,133602,5.2,1.000,6003.0,13.0,4.275000e+06,1113.0

In [213]:
# Read data from California wildfire insurance
wildfire_insurance = pd.read_excel("../../02_processed_data/Residential-Property-Coverage-Amounts-Wildfire-Risk-and-Losses_Export.xlsx", 
sheet_name="Export_all", header=2)
wildfire_insurance.head()

,Source,Calendar Year,Policy Type,ZIP Code,Avg Cov A,Avg Cov C,Avg PPC Class,Avg Fire Risk,Count N,Count L,...,NonCat CovC Smoke Count,Cat CovA Fire Losses,Cat CovA Fire Count,Cat CovA Smoke Losses,Cat CovA Smoke Count,Cat CovC Fire Losses,Cat CovC Fire Count,Cat CovC Smoke Losses,Cat CovC Smoke Count,County
0,All Companies,18,CO,90001,54454.53,79376.32,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,Los Angeles
1,All Companies,19,CO,90001,123721.07,154296.95,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,Los Angeles
2,All Companies,20,CO,90001,23037.32,44099.54,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,Los Angeles
3,All Companies,18,DO,90001,230821.52,20971.27,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,Los Angeles
4,All Companies,19,DO,90001,243257.71,21405.82,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,Los Angeles

In [214]:
# Subset data from 2018-2020, with homeowner premium insurance type
wildfire_insurance['Calendar Year'] += 2000
wildfire_insurance_18_20 = wildfire_insurance[
    (wildfire_insurance['Policy Type'] == "HO") & (wildfire_insurance['Calendar Year'].between(2018, 2020))]

# Keep the column of interest
wildfire_insurance_18_20 = wildfire_insurance_18_20[["Calendar Year", "ZIP Code", "Earned Prem", "Earned Exp"]]

In [215]:
# Load crosswalk file
crosswalk = pd.read_excel("../../01_original_data/ZIP_COUNTY_122020.xlsx", dtype={'ZIP': str, 'COUNTY': str})
crosswalk.head()

     ZIP COUNTY  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0  00501  36103   0.000000   1.000000   0.000000   1.000000
1  00601  72001   0.839799   0.800983   0.871166   0.838115
2  00601  72113   0.160201   0.199017   0.128834   0.161885
3  00602  72003   1.000000   0.998801   1.000000   0.999919
4  00602  72005   0.000000   0.001199   0.000000   0.000081

In [216]:
# Keep only the data from California
crosswalk_ca = crosswalk[crosswalk['ZIP'].str.startswith('9')]
crosswalk_ca.head()

         ZIP COUNTY  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
49760  90001  06037        1.0        1.0        1.0        1.0
49761  90002  06037        1.0        1.0        1.0        1.0
49762  90003  06037        1.0        1.0        1.0        1.0
49763  90004  06037        1.0        1.0        1.0        1.0
49764  90005  06037        1.0        1.0        1.0        1.0

In [217]:
# Force the zipcode to be a string
wildfire_insurance_18_20['ZIP Code'] = wildfire_insurance_18_20['ZIP Code'].astype(str)

# Keep only the largest res_ratio county for each zipcode to avoid 1 to many merge issue
crosswalk_ca['RES_RATIO'] = crosswalk_ca['RES_RATIO'].astype(float)
crosswalk_ca_sorted = crosswalk_ca.sort_values(by=['ZIP', 'RES_RATIO'], ascending=[True, False])
crosswalk_main = crosswalk_ca_sorted.drop_duplicates(subset=['ZIP'], keep='first')

# Merge the wildfire_insurance file with the crosswalk
wildfire_zip = wildfire_insurance_18_20.merge(
    crosswalk_main[['ZIP', 'COUNTY']], 
    left_on='ZIP Code', right_on='ZIP', 
    how='left'
)

/var/folders/6q/jjdxqy5114dgzjyg60l84np80000gn/T/ipykernel_29626/3822516419.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crosswalk_ca['RES_RATIO'] = crosswalk_ca['RES_RATIO'].astype(float)

In [218]:
wildfire_zip.head()

   Calendar Year ZIP Code  Earned Prem  Earned Exp    ZIP COUNTY
0           2018    90001      1233018        1799  90001  06037
1           2019    90001      1351943        1863  90001  06037
2           2020    90001      1496492        1908  90001  06037
3           2018    90002      1721682        2517  90002  06037
4           2019    90002      1923430        2660  90002  06037

In [219]:
# Add the 0 to county fips code 
df_ca_2018_2020["county_fips5"] = df_ca_2018_2020["county_fips5"].astype(str).str.zfill(5)

wildfire_zip = wildfire_zip.rename(columns={"COUNTY": "county_fips5", "Calendar Year": "yr"})

# Merge and get the final dataframe
final_df = wildfire_zip.merge(
    df_ca_2018_2020,
    on=['county_fips5', 'yr'],
    how='left'
)

/var/folders/6q/jjdxqy5114dgzjyg60l84np80000gn/T/ipykernel_29626/3499580463.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ca_2018_2020["county_fips5"] = df_ca_2018_2020["county_fips5"].astype(str).str.zfill(5)

In [220]:
final_df = final_df.drop(columns=["ZIP"])

# Create premium per unit to show average earned premium for each housing unit
final_df = final_df[final_df['Earned Exp'] > 0]
final_df['prem_per_unit'] = final_df['Earned Prem'] / final_df['Earned Exp']

In [221]:
final_df.head()

,yr,ZIP Code,Earned Prem,Earned Exp,county_fips5,hpi_change,hpi,state,flood_frequency,flood_property_damage,...,injuries_hurricane,damage_hurricane,real_gdp,unemployment_rate,prop_rate,county_fips,total_home_purchase,total_amt_purchase,total_population,prem_per_unit
0,2018,90001,1233018,1799,06037,6.71,1566.79,CALIFORNIA,0.0,0.0,...,0.0,0.0,740088358,4.6,1.175,6037.0,52076.0,3.046519e+10,10061533.0,685.390773
1,2019,90001,1351943,1863,06037,3.50,1621.68,CALIFORNIA,0.0,0.0,...,0.0,0.0,767859358,4.5,1.182,6037.0,53991.0,3.281898e+10,10011602.0,725.680623
2,2020,90001,1496492,1908,06037,2.72,1665.85,CALIFORNIA,2.0,0.0,...,0.0,0.0,729068982,12.3,1.171,6037.0,55477.0,3.715788e+10,9996634.0,784.324948
3,2018,90002,1721682,2517,06037,6.71,1566.79,CALIFORNIA,0.0,0.0,...,0.0,0.0,740088358,4.6,1.175,6037.0,52076.0,3.046519e+10,10061533.0,684.021454
4,2019,90002,1923430,2660,06037,3.50,1621.68,CALIFORNIA,0.0,0.0,...,0.0,0.0,767859358,4.5,1.182,6037.0,53991.0,3.281898e+10,10011602.0,723.093985